spring:
#  rsocket:
#    server:
#      transport: tcp
#      port: 7002
  zipkin:
    base-url: http://localhost:9411/
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      rate: 20
  application:
    name: client

rsocket.port: 7001

server:
  port: 8080

logging:
  level:
    io.rsocket: debug