spring:
  rsocket:
    server:
      transport: tcp
      port: 7001
  zipkin:
    base-url: http://localhost:9411/
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      rate: 20
  application:
    name: client

logging:
  level:
    io.rsocket: debug